### PR TITLE
Add title, description, change to dark skin

### PR DESCRIPTION
**Pull request by cthulhusec**

### CODE REVIEW

**Review by gathumann — APPROVED** [review]
Looks good!

**Review by rcarlson21 — COMMENTED** [review]
Is the only other option for theme Dark? I think light might would look better. What options do we have?

**Comment by cthulhusec** [comment]
> Is the only other option for theme Dark? I think light might would look better. What options do we have?

We could do light or dark. But dark is nicer on peoples eyes and should suit our content well. We could always change it back if it doesn't present well.

**Comment by rcarlson21** [comment]
Okay cool. I'm down with that then.

**Pull request merged**
